# Generated by Django 5.1.1 on 2024-10-01 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept', models.CharField(max_length=10)),
                ('code', models.CharField(max_length=10)),
                ('credit', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('prereqs', models.TextField(blank=True, null=True)),
                ('desc', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
