# Generated by Django 5.1.1 on 2024-10-02 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursedata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='course',
            name='credit',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='course',
            name='dept',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
