# Generated by Django 5.1.1 on 2024-10-02 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursedata', '0002_alter_course_code_alter_course_credit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='course',
            name='credit',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='course',
            name='dept',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='course',
            name='prereqs',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
